### PR TITLE
adds fantasy-checks

### PR DESCRIPTION
**Pull request by stoeffel**
I created some tests to check if `data.these` is fantasy-land compliant. Don't know if you are interested in adding this specs, I was just curious and created them :smile: Feel free to close this PR without merging.

### CODE REVIEW

**Comment by gilligan** [comment]
@stoeffel thanks a lot ! I will try to have a look at the changes in the evening!

**Comment by stoeffel** [comment]
cool! let me know if I have to change anything.

**Comment by stoeffel** [comment]
Btw. It would be nice to link to the FL specs in the readme, if you decide to merge this.

**Comment by gilligan** [comment]
@stoeffel will do. thanks for this.

**Comment by stoeffel** [comment]
Awesome!

**Comment by gilligan** [comment]
@stoeffel aeuhrm.. next time please check `npm run lint` - i should have added that to the `test` script.

**Comment by gilligan** [comment]
@stoeffel Also fantasy-identities and fantasy-combinators are not being used so i will remove them from package.json. Also the fantasy test uses template strings even though the remaining code is not written in es6 yet - i just changed that.

**Comment by stoeffel** [comment]
arg sorry didn't see the `lint` task.

**Pull request merged**
